
ERROR: Invalid requirement: 'from pip._vendor.packaging.specifiers import SpecifierSet' (from line 1 of ./venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/requirements.py)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 305, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 436, in get_requirements
    for parsed_req in parse_requirements(
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 145, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 326, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 331, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 360, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 533, in get_file_content
    content = auto_decode(f.read())
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/utils/encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 9: invalid start byte
ERROR: Invalid requirement: 'import re' (from line 5 of ./venv/lib/python3.8/site-packages/pip/_vendor/packaging/requirements.py)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 305, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 436, in get_requirements
    for parsed_req in parse_requirements(
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 145, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 326, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 331, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 360, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 533, in get_file_content
    content = auto_decode(f.read())
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/utils/encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 9: invalid start byte
ERROR: Invalid requirement: 'from __future__ import absolute_import, division, print_function' (from line 4 of ./venv/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 305, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 436, in get_requirements
    for parsed_req in parse_requirements(
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 145, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 326, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 331, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 360, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 533, in get_file_content
    content = auto_decode(f.read())
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/utils/encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 9: invalid start byte
ERROR: Invalid requirement: 'from __future__ import absolute_import, division, print_function' (from line 4 of ./venv/lib/python3.8/site-packages/setuptools/_vendor/packaging/requirements.py)
ERROR: Exception:
Traceback (most recent call last):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 305, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 436, in get_requirements
    for parsed_req in parse_requirements(
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 145, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 326, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 331, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 360, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 533, in get_file_content
    content = auto_decode(f.read())
  File "/root/IOCynergy/venv/lib/python3.8/site-packages/pip/_internal/utils/encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 9: invalid start byte
